#!/bin/bash
function wall() {
ls ~/scripts/4chan-walls/walls/ | sort -R |tail -$N |while read file; do
    feh --bg-fill walls/${file}
   case $(echo -e "Delete\nSave\nQuit\nDelete all" | dmenu -p "What do you want to do with this file?") in
    "Save")
	mv ~/scripts/4chan-walls/walls/${file} ~/wallpapers/
	;;
    "Delete")
	rm -rf ~/scripts/4chan-walls/walls/${file}
	;;
    "Quit")
	~/scripts/randomwall/randomwall
	exit 0
	;;
    "Delete all")
	~/scripts/randomwall/randomwall
	rm -rf ~/scripts/4chan-walls/walls/*
	exit 0
	;;
    esac
    wall
    break
done
}
wall